language: java
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

env:
  matrix:
    - LABEL=gradle     CMD="./gradlew build"

script:
  - jdk_switcher use oraclejdk8
  - ${CMD}

branches:
  only:
    - master
